<?php

namespace App\Views;

use App\app;
use Core\View;

class Navigation extends View
{

    public function __construct()
    {
        parent::__construct($this->generate());
    }

    public function generate()
    {

        if (App::$session->getUser()) {
            if (App::$session->getUser()['role'] == 'admin') {
                return [
                    App::$router::getUrl('index') => 'Home',
                    App::$router::getUrl('admin_order') => 'Orders',
                    App::$router::getUrl('users_list') => 'Users',
                    App::$router::getUrl('logout') => 'Logout',
                ];
            } else {
                return [
                    App::$router::getUrl('index') => 'Home',
                    App::$router::getUrl('my_orders') => 'My Orders',
                    App::$router::getUrl('logout') => 'Logout',
                ];
            }
        }
        if (!App::$session->getUser()) {
            return [
                App::$router::getUrl('index') => 'Home',
                App::$router::getUrl('register') => 'Register',
                App::$router::getUrl('login') => 'Login',
            ];
        }

    }

    public function render($template_path = ROOT . '/app/templates/nav.tpl.php')
    {
        return parent::render($template_path); // TODO: Change the autogenerated stub
    }
}